Add labelmap2vec.
JuliaML/MLLabelUtils.jl pull request #29
Opened 2018-11-17 15:13 UTC by holtri

This adds functionality to convert a labelmap into a label vector.

Example:

```julia
julia> labelvec = [:yes,:no,:no,:yes,:yes]
5-element Array{Symbol,1}:
 :yes
 :no
 :no
 :yes
 :yes

julia> lm = labelmap(labelvec)
Dict{Symbol,Array{Int64,1}} with 2 entries:
  :yes => [1, 4, 5]
  :no  => [2, 3]

julia> labelmap2vec(lm)
5-element Array{Symbol,1}:
 :yes
 :no
 :no
 :yes
 :yes

```

2018-11-17 15:33 UTC, holtri commented
Coverage decrease seems to be related to issues with coverage reporting: https://github.com/JuliaCI/Coverage.jl/issues/187 
https://github.com/JuliaLang/julia/issues/28192

2018-11-18 10:01 UTC, Evizero requested changes
I can see how this could be useful, thanks!

I order for me to merge could you do one of the following two things:

- add a docstring to `labelmap2vec` and an entry for it in the docs.
- not export `labelmap2vec`

2018-11-18 10:14 UTC, oxinabox commented
I think the docstring should mention it is the inverse function of `labelmap`

2018-11-19 12:15 UTC, Evizero approved these changes

2018-11-19 12:16 UTC, merged

2018-11-19 12:16 UTC, Evizero commented
thanks!